[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip RP2040"
rustflags = [ "-C", "link-arg=-Map=hwtest.map" ]

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
